### PR TITLE
Entry For Zhenyu

### PR DESCRIPTION
**Pull request by ZhenyuYu1**

### CODE REVIEW

**Review by ngillux — CHANGES_REQUESTED** [review]
Part of the task is to include an image, are you able to add an image?

**Comment by ZhenyuYu1** [comment]
> Part of the task is to include an image, are you able to add an image?

Hi I added the picture in a new pull request, but I'm not sure if it worked since it won't let me run the page again.

**Comment by ZhenyuYu1** [comment]
I think I fixed it but I'm not sure. Can you see if it worked?

**Comment by ngillux** [comment]
Hi @ZhenyuYu1 everything looks good to me, what do you mean by it won't let you run the page again? Looping in Utsab before merging.

**Comment by ZhenyuYu1** [comment]
Nevermind, it just didn't let me launch the page initially but it worked when I restarted the codespace.

**Pull request closed without merging**
