### PR TITLE
Added an entry for Sherman Zhang

### PR DESCRIPTION
**Pull request by alszzy**

### CODE REVIEW

**Comment by hisergiorojas** [comment]
You pull request did not include an image. Please add another commit that includes an image

**Comment by hisergiorojas** [comment]
You pull request did not include an image. Please add another commit that includes an image

**Comment by alszzy** [comment]
I've added the image.

**Comment by hisergiorojas** [comment]
Your pull request included a python binary cache. Please add another commit that removes the python binary cache

**Pull request merged**
